name: neuro-workflow

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./workflow_backend/.env
    # ports:
    #   - "5432:5432"
    networks:
      - workflow

  backend:
    build: ./workflow_backend
    command: bash -c "python3 django-project/manage.py makemigrations && python3 django-project/manage.py migrate && python3 django-project/manage.py runserver 0.0.0.0:3000"
    volumes:
      - ./workflow_backend:/django-app
      - ${NODES_DIR}:/django-app/django-project/codes/nodes
    working_dir: /django-app
    # ports:
    #   - "3000:3000"
    env_file:
      - ./workflow_backend/.env
    depends_on:
      - db
    networks:
      - workflow
      - jupyterhub-network

  jupyterhub:
    build: ./workflow_backend/django-project/neuroworkflow
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./workflow_backend/django-project/neuroworkflow/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - jupyterhub-data:/srv/jupyterhub
    restart: unless-stopped
    networks:
      - jupyterhub-network

  frontend:
    build: ./workflow_frontend
    command: npm run dev:docker
    ports:
      - "5173:5173"
    env_file:
      - ./workflow_frontend/.env
    depends_on:
      - backend 
    networks:
      - workflow

  mcp:
    build: ./mcp_server
    command: python3 ./proxy.py
    environment:
      - MCP_PROXY_PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - ./mcp_server/mcp_config.json:/app/mcp_config.json
    depends_on:
      - backend 
    networks:
      - workflow

volumes:
  postgres_data:
  jupyterhub-data:

networks:
  workflow:
  jupyterhub-network:
    name: jupyterhub-network
